// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcCzLBvgxjgNwI881ZZ4ls33B675aeDTY',
    appId: '1:434635145729:web:dd5c54bb9a1366c9b03600',
    messagingSenderId: '434635145729',
    projectId: 'salonlogin-fbbdd',
    authDomain: 'salonlogin-fbbdd.firebaseapp.com',
    storageBucket: 'salonlogin-fbbdd.appspot.com',
    measurementId: 'G-4M4F19WC73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEGqHrT0iYmZH3HKwYwE8LYjQi3ybdos',
    appId: '1:434635145729:android:00d37ac449ffd99ab03600',
    messagingSenderId: '434635145729',
    projectId: 'salonlogin-fbbdd',
    storageBucket: 'salonlogin-fbbdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgn2DEWVKWPlK5A1Y_eLLqTTUzsyXwHw',
    appId: '1:434635145729:ios:c7a079119a8b7696b03600',
    messagingSenderId: '434635145729',
    projectId: 'salonlogin-fbbdd',
    storageBucket: 'salonlogin-fbbdd.appspot.com',
    androidClientId: '434635145729-t7ovam357i5i8sfflhuhduniiad0tsec.apps.googleusercontent.com',
    iosClientId: '434635145729-v128r3j2d6pr2fidbc549ele2j6ug5pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftstyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdgn2DEWVKWPlK5A1Y_eLLqTTUzsyXwHw',
    appId: '1:434635145729:ios:7cfd762dc5791687b03600',
    messagingSenderId: '434635145729',
    projectId: 'salonlogin-fbbdd',
    storageBucket: 'salonlogin-fbbdd.appspot.com',
    androidClientId: '434635145729-t7ovam357i5i8sfflhuhduniiad0tsec.apps.googleusercontent.com',
    iosClientId: '434635145729-3v7aral608n6ctm3hbhn9l0j1te27jfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftstyle.RunnerTests',
  );
}
